apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-05-01T18:22:20Z"
  labels:
    app: nginx-svc
  name: nginx-svc
  namespace: default
  uid: a70458a4-9e90-4c67-9226-3623dc0e7611
spec:
  clusterIP: 10.96.0.0
  clusterIPs:
  - 10.96.0.0
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 80-3000
    nodePort: 32769
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: nginx-svc
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
